css:
    filename: output/css/{{ scheme-system }}-{{ scheme-slug }}.css
css-variables:
    filename: output/css-variables/{{ scheme-system }}-{{ scheme-slug }}.css
less:
    filename: output/less/{{ scheme-system }}-{{ scheme-slug }}.less
sass:
    filename: output/sass/{{ scheme-system }}-{{ scheme-slug }}.sass
scss:
    filename: output/scss/{{ scheme-system }}-{{ scheme-slug }}.scss
stylus:
    filename: output/stylus/{{ scheme-system }}-{{ scheme-slug }}.styl
